linters-settings:
  # Enable only minimal linting to reduce code issues
  govet:
    enable: false
  staticcheck:
    enable: false
  errcheck:
    enable: false

run:
  skip-dirs:
    - vendor
  skip-files:
    - "*.test.go"
